### PR TITLE
Added: Light Theme Mode

### PR DESCRIPTION
**Pull request by GaganpreetKaurKalsi**
#44 : Successfully added Light Mode to caucus

I have added classes such as tone1, tone2, tone3 to the components. In future, if you would like to add other themes to the components, you just need to specify it in the Theme.style.css file. Below are some screenshots for your reference.
image
image
image
image
image

Kindly review and let me know if I need to do something on my part.
Thanks!

### CODE REVIEW

**Comment by Rishabh-malhotraa** [comment]
I am not a big fan of how CSS modules way of switching themes. I am tempted to switch to styled-components for all things CSS, but that would be a big restructure. What do you think?

**Comment by GaganpreetKaurKalsi** [comment]
I have made all the requested changes. You can have a look now!

**Comment by Rishabh-malhotraa** [comment]
@GaganpreetKaurKalsi After doing some research about how to implement different themes, I think CSS modules would work well too, we just need to do some workaround.


- Since MUI injects the CSS at the end of the HTML it takes precedence over all the CSS we write in our `css.modules` file and we have to write `!important` everywhere, we can fix this by using 
``` jsx
<StyledEngineProvider injectFirst>
  {/* Your component tree. Now you can override MUI's styles. */}
</StyledEngineProvider>
```
[MUI Docs Explaining the same](https://mui.com/guides/interoperability/#css-modules)

If we do this we can also remove all the CSS-in-JS we have used at different places, like we do [here](https://github.com/Rishabh-malhotraa/caucus/blob/main/src/component/InputOutputFile/InputOutputFile.tsx)


- the way I want to implement different themes is by using a JSON object and change the CSS-variable values using JS

``` js
const lightTheme = {
  "--primary": "#31e981",
  "--seconday": "#000000",
  };

//This is our dark mode
const darkTheme = {
  "--primary": "#286843",
  "--seconday": "#ffffff",
};
export { lightTheme, darkTheme };
```

``` js
const ApplyTheme = ({ theme, children }) => {
  //Update the CSS Variables
  const updateCSSVariables = theme => {
    const arrayOfVariableKeys = Object.keys(theme);
    const arrayOfVariableValues = Object.values(theme);

    //Loop through each array key and set the CSS Variables
    arrayOfVariableKeys.forEach((cssVariableKey, index) => {
      //Based on our snippet from MDN
      document.documentElement.style.setProperty(
        cssVariableKey,
        arrayOfVariableValues[index]
      );
    });
  };
```
[Here](https://blog.bitsrc.io/theming-react-applications-with-css-variables-and-react-redux-8be0b10d829f) is an article which explains theming in details

**Comment by GaganpreetKaurKalsi** [comment]
> @GaganpreetKaurKalsi After doing some research about how to implement different themes, I think CSS modules would work well too, we just need to do some workaround.
> 
> * Since MUI injects the CSS at the end of the HTML it takes precedence over all the CSS we write in our `css.modules` file and we have to write `!important` everywhere, we can fix this by using
> 
> ```js
> <StyledEngineProvider injectFirst>
>   {/* Your component tree. Now you can override MUI's styles. */}
> </StyledEngineProvider>
> ```
> 
> [MUI Docs Explaining the same](https://mui.com/guides/interoperability/#css-modules)
> 
> If we do this we can also remove all the CSS-in-JS we have used at different places, like we do [here](https://github.com/Rishabh-malhotraa/caucus/blob/main/src/component/InputOutputFile/InputOutputFile.tsx)
> 
> * the way I want to implement different themes is by using a JSON object and change the CSS-variable values using JS
> 
> ```js
> const lightTheme = {
>   "--primary": "#31e981",
>   "--seconday": "#000000",
>   };
> 
> //This is our dark mode
> const darkTheme = {
>   "--primary": "#286843",
>   "--seconday": "#ffffff",
> };
> export { lightTheme, darkTheme };
> ```
> 
> ```js
> const ApplyTheme = ({ theme, children }) => {
>   //Update the CSS Variables
>   const updateCSSVariables = theme => {
>     const arrayOfVariableKeys = Object.keys(theme);
>     const arrayOfVariableValues = Object.values(theme);
> 
>     //Loop through each array key and set the CSS Variables
>     arrayOfVariableKeys.forEach((cssVariableKey, index) => {
>       //Based on our snippet from MDN
>       document.documentElement.style.setProperty(
>         cssVariableKey,
>         arrayOfVariableValues[index]
>       );
>     });
>   };
> ```
> 
> [Here](https://blog.bitsrc.io/theming-react-applications-with-css-variables-and-react-redux-8be0b10d829f) is an article which explains theming in details

Okay! I got it. But this workaround is quite huge. I would suggest you merge this pull request first and open up another issue and assign that to me. I will work on it then. Also it would be great if you could merge the others as well, as I am participating in Hacktoberfest for the first time and it means a lot to me.
Thanks!

**Pull request closed without merging**
