### PR TITLE
added contrast on hover for problem list

### LINKED ISSUE #30: Improving Contrast on hover
Currently, there is no contrast on hover on list items.

image

image

### PR DESCRIPTION
**Pull request by chirag3003**
closes #30

### CODE REVIEW

**Comment by chirag3003** [comment]
pls give this pr a label of `hacktoberfest-accepted`

**Comment by Rishabh-malhotraa** [comment]
Would you please add a screenshot of how the hover looks now, Thanks!

**Comment by chirag3003** [comment]
#30

**Comment by chirag3003** [comment]
> Would you please add a screenshot of how the hover looks now, Thanks!

hover-screenshot

**Comment by chirag3003** [comment]
@Rishabh-malhotraa when will u merge?

**Comment by Rishabh-malhotraa** [comment]
> @Rishabh-malhotraa when will u merge?
> 

I'll merge it as soon as I can get time to check out the changes locally on my computer, I'm a bit busy with college assignments, _I'll merge it by the end of week positively. _

**Comment by chirag3003** [comment]
@Rishabh-malhotraa can u check this pr cause it will only be accepted for hactoberfest when merged

**Comment by Rishabh-malhotraa** [comment]
LGTM, thank you!

**Comment by Rishabh-malhotraa** [comment]
@all-contributors please add @chirag3003

**Comment by Rishabh-malhotraa** [comment]
@all-contributors please add @chirag3003  for design

**Pull request merged**
