### PR TITLE
added hover effect to problem list

### PR DESCRIPTION
**Pull request by mthakur7**
Hi Rishabh,
I have added hover effect to problem list, please have a look. Kindly merge it.

### CODE REVIEW

**Comment by Rishabh-malhotraa** [comment]
Thank you for the PR!

**Comment by mthakur7** [comment]
Hi @Rishabh-malhotraa ,
Kindly merge it. Please accept it under Hactoberfest'21. I request you

**Comment by Rishabh-malhotraa** [comment]
Thanks for the PR, LGTM! 🙌🏻

**Comment by Rishabh-malhotraa** [comment]
@all-contributors please add @mthakur7

**Comment by Rishabh-malhotraa** [comment]
@all-contributors please add @mthakur7 for design

**Pull request merged**
